#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH=$PATH:~/bin/Sencha/Cmd/5.0.1.231/
export GEM_HOME='/usr/local/Cellar/gems/1.8'


### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# z terminal navigation
# assumes z installed.
. `brew --prefix`/etc/profile.d/z.sh

## use mvim
alias vi="mvim -v"

# GOPATHs
export GOPATH="${HOME}/go"
export PATH=$PATH:/$GOPATH/bin
export PATH=$PATH:$GOPATH
# Docker env
export DOCKER_HOST=tcp://192.168.59.103:2376
export DOCKER_CERT_PATH=/Users/simon/.boot2docker/certs/boot2docker-vm
export DOCKER_TLS_VERIFY=1
