set nocompatible
call pathogen#infect()

set nocp

syntax on
filetype plugin indent on

set number
set ruler
set nowrap
set encoding=utf-8

set tabstop=2
set shiftwidth=2
set softtabstop=2

set expandtab
set incsearch
set ignorecase
set showmatch
set smartcase

au BufRead,BufNewFile {Gemfile,Rakefile,Vagrantfile,Thorfile,config.ru} set ft=ruby
au BufRead,BufNewFile {*.json} set ft=javascript
au BufRead,BufNewFile {*.txt} call s:setupWrapping()

function s:setupWrapping()
  set wrap
  set wrapmargin=2
  set textwidth=72
endfunction

let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'

" ignore these files when completing names and in Ex
set wildignore=.svn,CVS,.git,*.o,*.a,*.class,*.mo,*.la,*.so,*.obj,*.swp,*.jpg,*.png,*.xpm,*.gif,*.pdf,*.bak,*.beam
" set of file name suffixes that will be given a lower priority when it comes to matching wildcards
set suffixes+=.old

set guifont=Monospace\ 8

set backspace=indent,eol,start

color desert

nnoremap ,m :w <BAR> !lessc % > %:t:r.css<CR><space>

" CTAGS
set tags+=~/.vim/tags/stl

" build tags of your own project with CTRL+F12
"map <C-F12> :!ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<CR>
noremap <F12> :!ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<cr>
inoremap <F12> <Esc>:!ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<cr>

" OmniCppComplete
let OmniCpp_NamespaceSearch = 1
let OmniCpp_GlobalScopeSearch = 1
let OmniCpp_ShowAccess = 1
let OmniCpp_MayCompleteDot = 1
let OmniCpp_MayCompleteArrow = 1
let OmniCpp_MayCompleteScope = 1
let OmniCpp_DefaultNamespaces = ["std", "_GLIBCXX_STD"]

au CursorMovedI,InsertLeave * if pumvisible() == 0|silent! pclose|endif
set completeopt=menuone,menu,longest,preview
set rtp+=$GOPATH/src/github.com/golang/lint/misc/vim
